# Generated by Django 4.0 on 2026-01-22 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipl_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='franchise',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
