# Generated by Django 4.0 on 2026-01-23 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipl_app', '0002_alter_franchise_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('role', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=50)),
                ('franchise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipl_app.franchise')),
            ],
            options={
                'db_table': 'players',
            },
        ),
    ]
