# Generated by Django 4.2.7 on 2026-01-28 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipl_app', '0004_player_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='stadium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipl_app.franchise')),
            ],
        ),
    ]
